server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/vn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.myapp.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






